import { BuiltinMask } from "./typing";
export const CN_MASKS: BuiltinMask[] = [
  {
    avatar:"gpt-bot",
    name: "中国计算机协会-130B",
    context: [],
    modelConfig: {
      model: "chatglm-130b-api",
      temperature: 0,
      max_tokens: 4000,
      presence_penalty: 0,
      institution: "中国计算机协会",
      sendMemory: false,
      historyMessageCount: 10,
      compressMessageLengthThreshold:123456789,
    },
    lang: "cn",
    builtin: true,
  },
  {
    avatar:"gpt-bot",
    name: "中国计算机协会-6B",
    context: [],
    modelConfig: {
      model: "chatglm-6b-api",
      temperature: 0,
      max_tokens: 4000,
      presence_penalty: 0,
      institution: "中国计算机协会",
      sendMemory: false,
      historyMessageCount: 10,
      compressMessageLengthThreshold:123456789,
    },
    lang: "cn",
    builtin: true,
  },
  {
    avatar:"gpt-bot",
    name: "安徽大学-130B",
    context: [],
    modelConfig: {
      model: "chatglm-130b-api",
      temperature: 0,
      max_tokens: 4000,
      presence_penalty: 0,
      institution: "安徽大学",
      sendMemory: false,
      historyMessageCount: 10,
      compressMessageLengthThreshold:123456789,
    },
    lang: "cn",
    builtin: true,
  },
  {
    avatar:"gpt-bot",
    name: "安徽大学-6B",
    context: [],
    modelConfig: {
      model: "chatglm-6b-api",
      temperature: 0,
      max_tokens: 4000,
      presence_penalty: 0,
      institution: "安徽大学",
      sendMemory: false,
      historyMessageCount: 10,
      compressMessageLengthThreshold:123456789,
    },
    lang: "cn",
    builtin: true,
  },
  {
    avatar:"gpt-bot",
    name: "中山大学-130B",
    context: [],
    modelConfig: {
      model: "chatglm-130b-api",
      temperature: 0,
      max_tokens: 4000,
      presence_penalty: 0,
      institution: "中山大学",
      sendMemory: false,
      historyMessageCount: 10,
      compressMessageLengthThreshold:123456789,
    },
    lang: "cn",
    builtin: true,
  },
  {
    avatar:"gpt-bot",
    name: "中山大学-6B",
    context: [],
    modelConfig: {
      model: "chatglm-6b-api",
      temperature: 0,
      max_tokens: 4000,
      presence_penalty: 0,
      institution: "中山大学",
      sendMemory: false,
      historyMessageCount: 10,
      compressMessageLengthThreshold:123456789,
    },
    lang: "cn",
    builtin: true,
  },
  {
    avatar:"gpt-bot",
    name: "清华大学-130B",
    context: [],
    modelConfig: {
      model: "chatglm-130b-api",
      temperature: 0,
      max_tokens: 4000,
      presence_penalty: 0,
      institution: "清华大学",
      sendMemory: false,
      historyMessageCount: 10,
      compressMessageLengthThreshold:123456789,
    },
    lang: "cn",
    builtin: true,
  },
  {
    avatar:"gpt-bot",
    name: "清华大学-6B",
    context: [],
    modelConfig: {
      model: "chatglm-6b-api",
      temperature: 0,
      max_tokens: 4000,
      presence_penalty: 0,
      institution: "清华大学",
      sendMemory: false,
      historyMessageCount: 10,
      compressMessageLengthThreshold:123456789,
    },
    lang: "cn",
    builtin: true,
  },
  
  {
    avatar:"gpt-bot",
    name: "ChatGLM-130B",
    context: [],
    modelConfig: {
      model: "chatglm-130b-api",
      temperature: 0,
      max_tokens: 4000,
      presence_penalty: 2,
      institution: "",
      sendMemory: false,
      historyMessageCount: 10,
      compressMessageLengthThreshold:123456789,
    },
    lang: "cn",
    builtin: true,
  },
  {
    avatar:"gpt-bot",
    name: "ChatGLM-6B",
    context: [],
    modelConfig: {
      model: "chatglm-6b-api",
      temperature: 0,
      max_tokens: 2000,
      presence_penalty: 2,
      institution: "",
      sendMemory: false,
      historyMessageCount: 10,
      compressMessageLengthThreshold:123456789,
    },
    lang: "cn",
    builtin: true,
  },
];